name: Test

on:
  pull_request:
  workflow_dispatch:

env:
  package: MediaViewer

jobs:
  test:
    runs-on: macos-26
    
    env:
      IOS_SIMULATOR: "iPhone 17"
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Build for testing
        run: xcodebuild build-for-testing -scheme ${{ env.package }} -destination "platform=iOS Simulator,OS=latest,name=${{ env.IOS_SIMULATOR }}"
        
      - name: Run tests
        run: xcodebuild test-without-building -scheme ${{ env.package }} -destination "platform=iOS Simulator,OS=latest,name=${{ env.IOS_SIMULATOR }}"
